### ISSUE TITLE
US6 - Editing Recipes

### ISSUE THREAD

**Issue by Leviron** [Leviron/Capstone-project#13]
## Value Proposition

As a user I want to be able to edit my recipes in the app to ensure they are accurate and up to-date
​

## Description
<img width="961" alt="Bildschirmfoto 2023-08-04 um 14 17 00" src="https://github.com/Leviron/Capstone-project/assets/133430381/db980a0b-5b6b-471f-8c64-5bd78e58e94c">

​

- [x] An "Edit" button exists on every Recipe in the recipe detail page and on the Main page
- [x] Allow the user to modify the recipe
- [x] Implement a "Save" button to apply the changes made during editing.

## Tasks

- [x] Add "Edit" button to the recipe detail page and to the card in the main page.
- [x] Create a form to edit recipe details and updates the database.
- [x] Implement the "Save" functionality and update the database with changes.

**Comment by CJAkkuec** [comment]
Here

**i**
🫴

You dropped an "i" in your title.
And there's a little bit of a formatting "oops" as far as your first AC is concerned.

Other than that, I'm a little curious why you've chosen to move the edit feature to just the detail page. Wouldn't it be a little more user-friendly to perhaps include the edit button in the overview items also? Might same some users a click. :)
