### ISSUE TITLE
US7 - Add Favorite and Like Button

### ISSUE THREAD

**Issue by Leviron** [Leviron/Capstone-project#14]
## Value Proposition

As a user  I want the ability to mark items from my List so I can easily keep track of my favorite content.

## Description

<img width="595" alt="Bildschirmfoto 2023-08-04 um 14 23 32" src="https://github.com/Leviron/Capstone-project/assets/133430381/1b431ca5-8957-4eb4-9bf3-ed966dfdaa7e">

​

## Acceptance Criteria

- [ ] Add a "Favorite" button/icon to every Card at the main page
- [ ] Add a "Like" button/icon to every Card at the main page
- [ ] After clicking the "Favorite" the recipe should be added to a List
- [ ] Clicking the "Like" button on an item, should counting the Likes.​

## Tasks

- [ ]  Create a "Favorite" and "Like" button
- [ ]  Update the DB schema 
- [ ] Create a "My Recipes" page
- [ ] Add functionality to the buttons
