### ISSUE TITLE
US1 - List of recipes

### ISSUE THREAD

**Issue by Leviron** [Leviron/Capstone-project#2]
## Value Proposition

As a User I want to see a list of recipes, so that I can get an overview of all recipes.

## Acceptance Criteria
![Bildschirmfoto 2023-07-20 um 11 18 37](https://github.com/Leviron/Capstone-project/assets/133430381/321b5bd5-8132-4a42-ab50-6768d32cd6ec)

- [x] all recipes are visible (5 examples)
- [x]  the recipe have a title and a picture
- [x] the recipes are displayed in a card

## Tasks

- [x]  Create the component Recipe for a individual recipe
- [x]  The component Recipe contains id, picture , title and subtitle
- [x]  Create a list with at least 5 example recipes

**Comment by Roland-Hufnagel** [comment]
Hi Ron, good start for your first userstory. I think you got good inspiration by Frank's userstory 😀 (Please redefine your second acceptance-criteria)
Okay. You have a good start but some points to mention:
- The title 'US1' is to small and won't tell anything about the story
- Don't overwrite the markdown format in the template (it is used to display checkboxes)
- Your wireframe should only show the features from this story (and from earlier stories)

So I think it needs a little bit of work and then it will be fine. Please post an updated version.

**Comment by actyvystom** [comment]
Hi Ron, 
please stick to what @Roland-Hufnagel said regarding the title.
Your value proposition does not follow the correct syntax, so please try to put in a way that follows 
> as a user I want to ... so that ...

Additionally it contains too many features (see, edit and create), so please try to narrow it down to one feature. After that, your acceptance criteria needs to be adjusted accordingly.

**Comment by Roland-Hufnagel** [comment]
Please read the comments carefully.
- The title of the userstory is still "US1". Please use a more informative title
- 'US1' should not be visible in your wireframe
- your wireframe still shows features that are not part of your app at this time. Please remove them

**Comment by Roland-Hufnagel** [comment]
That is fine now. I only found one conflict: Since the acceptance-criteria says: 'the recipe have a title and a picture' the task cannot make the picture optional. Please solve that conflict and than you are ready to go...🎉
