### ISSUE TITLE
US2 - search function 

### ISSUE THREAD

**Issue by Leviron** [Leviron/Capstone-project#3]
## Value Proposition

As a User I want to filter the recipes, so that I can get the matching recipe.
​

## Description

![Image](https://github.com/Leviron/Capstone-project/assets/133430381/d024e160-0d6b-492f-a321-80f51962d0a0)

## Acceptance Criteria

- [x] The search function is prominently placed within the app
- [x] The search area includes an input field where I can enter either the title of a dish
- [x] The search results are presented in a clear list format, with each result displaying the recipe with a title and a picture
      ​

## Tasks

- [x] create a feature branch
- [x] Design the search user interface (UI) with a prominent search icon and input field in the navigation bar
- [x] Implement the search functionality to handle search queries and display relevant results

**Comment by VolkerJacobsen** [comment]
Hi Leviron, nice Userstory. Just a quick question. The filter dispayed on top is the searchbar,right? If so you should maybe call it search box instead of filter? What is the submit button for? If it is for the search box you know that you could handle the search also via input and don´t need to submit the search terms, right?
