### ISSUE TITLE
US4 - Create new recipe

### ISSUE THREAD

**Issue by Leviron** [Leviron/Capstone-project#5]
## Value Proposition

As a User I want to create my own recipes so that they are displayed on the app's main page.

## Description
<img width="895" alt="Bildschirmfoto 2023-07-20 um 18 00 13" src="https://github.com/Leviron/Capstone-project/assets/133430381/8e87cb44-94bd-41a2-aa31-d5f54b364448">

## Acceptance Criteria

- [x] On the "home" page, there is a "+" button that allows users to navigate to the "Create Recipe" page.
- [x] The navigation bar should remain consistent and visible on all pages of the app.
- [x] The "Create Recipe" page contains input fields
- [x] Upon completing all the required fields, users can click the "Create" button on the "Create Recipe" page to save the recipe.
- [x] The "home" page of the app displays now the created recipe
- [x] Clicking on a recipe's  "more details " button leads to the detailed view of that specific recipe

## Tasks

- [x] create the "Create Recipe" page with the necessary input fields for recipe details and implement it in the app's 
- [x] Implement back-end functionality to handle the creation and storage of new recipes in the database.
- [x] Create a navigation bar on the home page with an "+" and "home" button that links to the "Create Recipe" or "home" page.
- [x] Clicking the "Home" button in the navigation bar takes the user back to the "home" page
- [x] Clicking the "+" button in the navigation bar takes the user to the "Create Recipe" page
- [x] Fetch and display the list of created recipes on the home page from the database

**Comment by ekat-br** [comment]
Hi @Leviron, nice user story!🚀

For the "Create Recipe" page, let's make it more precise. You'll be building a form that includes input fields with corresponding labels and a submit button. To maintain code organization, it's recommended to create a separate Component called "RecipeForm" and render it on the "Create Recipe" page.

Additionally, let's include acceptance criteria for the navigation:
- The navigation bar should remain consistent and visible on all pages of the app.
- Clicking the "Home" button in the navigation bar takes the user back to the "home" page.
- Clicking the "+" button in the navigation bar takes the user to the "Create Recipe" page 

I hope this comment is clear. Please share the updated version  🚀

**Comment by ekat-br** [comment]
Hi, @Leviron now your user story looks good. One little thing: Your value proposition does not follow the correct syntax, so please try to put in a way that follows

as a user I want to ... so that ...

Please update this and post your US again. :)
