### ISSUE TITLE
US5 - Delete recipes

### ISSUE THREAD

**Issue by Leviron** [Leviron/Capstone-project#6]
## Value Proposition

As a user, I want to edit and delete recipes to keep my recipe database up-to-date and organized.

## Description

​
<img width="778" alt="Bildschirmfoto 2023-07-20 um 18 33 20" src="https://github.com/Leviron/Capstone-project/assets/133430381/e2a36a6d-7be7-42f9-8255-9e61b67eda31">

## Acceptance Criteria

- [x] Each recipe on the home page includes an "delete" button or Icon
- [x] Clicking on the delete button automatically deletes the respective recipe
- [x] If I delet an recipe,  its removed from the database.

## Tasks

- [x] Add an "delete" button or Icon to each recipe entry on the home page and implement the functionality to delete recipes.
- [x] implement the "Delete Recipe" functionality 
- [x] Set up the redirection to update the recipe list on the home page after successful deletion of a recipe.

**Comment by ekat-br** [comment]
Hi Ron, 

in the Value Proposition is missing the last part(in order to/so that...). For example you could write: As a user, I want to edit and delete recipes in order to keep my recipe database up-to-date and organized. 

Apart from that the user story looks really good to me. Keep up the good work and happy hacking🚀

**Comment by ekat-br** [comment]
LGTM🚀
